version: '3.8'

services:
  logstash:
    image: logstash:7.10.1
    container_name: logstash
    ports:
      - "5044:5044"       # Порт для получения логов от Jenkins
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_backend
    ports:
      - "8080:8080"       # Порт для WebSocket и HTTP-запросов от Logstash
    volumes:
      - ./logs.db:/app/logs.db  # Общий volume для хранения базы данных SQLite
