name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Cache Go modules
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    # Set up Go environment
    - name: Set up Go 1.23
      uses: actions/setup-go@v4
      with:
        go-version: 1.23

    # Install dependencies
    - name: Install dependencies
      run: go mod download

    # Install golint
    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    # Run golint
    - name: Run golint
      run: |
        # Run golint on the entire project
        gofmt -s -l . | golint | tee /dev/stderr | wc -l | xargs -I {} echo "Found {} issues"
        if [ {} -gt 0 ]; then exit 1; fi

    # Run the tests
    - name: Run Go tests
      run: go test -v ./...

    # Optional: Check for Go modules tidiness
    - name: Check Go modules
      run: go mod tidy -v

  dockerize:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Build and Push Docker image with Cache
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:${{ github.sha }}
          ghcr.io/${{ github.repository }}:latest
        cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:cache
        cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:cache,mode=max

    - name: Logout from GitHub Container Registry
      run: docker logout ghcr.io
      shell: bash